name: Build & Deploy ContosoUniversity (ASP.NET Core) to Azure Web App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 6.0.300
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.300'

    - name: Restore
      run: dotnet restore ./src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj

    - name: Publish (self-contained win-x86)
      run: dotnet publish ./src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj -c Release -r win-x86 --self-contained true -o ./publish

    - name: Zip artifact
      run: powershell -c "Compress-Archive -Path ./publish/* -DestinationPath ./web.zip"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: monitoring2-web
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./web.zip